version: '3.8'

services:
  nova-retail-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
